language: java

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean verify
  - mvn clean verify -P with-one-way-authentication
  - mvn clean verify -P with-two-way-authentication-by-trusting-root-ca
  - mvn clean verify -P with-two-way-authentication-by-trusting-each-other
