language: java
os: linux
sudo: true
install: true

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - switch-to-travis-ci

script:
  - "mvn clean install -P with-two-way-authentication-by-trusting-root-ca"


