language: java
os: linux

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - switch-to-travis-ci

script:
  - mvn clean verify
  - mvn clean verify -Pwith-one-way-authentication
  - mvn clean verify -Pwith-two-way-authentication-by-trusting-root-ca
  - mvn clean verify -Pwith-two-way-authentication-by-trusting-each-other


