language: java
os: linux
sudo: true
install: true

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - switch-to-travis-ci

jobs:
  include:
    - stage: "without-encryption"
    - script: "mvn clean verify -P without-authentication"
    - stage: "one-way-authentication"
    - script: "mvn clean verify -P with-one-way-authentication"
    - stage: "two-way-authentication-by-trusting-each-other"
    - script: "mvn clean verify -P with-two-way-authentication-by-trusting-each-other"
    - stage: "two-way-authentication-by-trusting-root-ca"
    - script: "mvn clean verify -P with-two-way-authentication-by-trusting-root-ca"
