name: Build

on: [push]

jobs:
  without-encryption:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - uses: actions/upload-artifact@master
        with:
          name: server-without-encryption
          path: server/target/server.jar

  one-way-authentication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install -P with-one-way-authentication

      - uses: actions/upload-artifact@master
        with:
          name: server-with-one-way-authentication
          path: server/target/server.jar

  two-way-authentication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean install -P with-two-way-authentication

    - uses: actions/upload-artifact@master
      with:
        name: server-with-two-way-authentication
        path: server/target/server.jar
